### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [ghlin/zsh-theme-daily#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by ghlin** [comment]
:grin:  done

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/803
